- console-extensions.json
- package-lock.json
- package.json
- yarn.lock
Re: https://github.com/Kuadrant/console-plugin/issues/25
> adding some navigation stubs for agreed layout

- package.json
- yarn.lock
Allows for later version of [ResourceYamlEditor](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/api.md#resourceyamleditor) props
> Bump dynamic sdk version

- src/utils/createResource.tsx
To use see example in https://github.com/Kuadrant/console-plugin/pull/52/files#diff-75017fdb2abfd575a647de98fdeac54a4156d480346c6a74f64c93542cdec41e
> Generic create function

- package-lock.json
- package.json
- yarn.lock
> babel-loader downgrade

- package.json
- src/components/DropdownWithKebab.tsx
- src/components/PolicyTopologyPage.tsx
- src/components/ResourceList.tsx
- src/components/kuadrant.css
- src/utils/getModelFromResource.ts
- src/utils/modelUtils.ts
- yarn.lock
New: Adds support for Patternfly Topology to render our topology.
> Patternfly Topology

- Dockerfile
- README.md
- entrypoint.sh
- install.yaml
- src/components/PolicyTopologyPage.tsx
see https://github.com/Kuadrant/kuadrant-operator/pull/920
resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/48
> Dynamic lookup for topology

- src/components/ResourceList.tsx
- src/components/kuadrant.css
- Fixes z-index weirdness with pagination in resource lists (shift the pagination to the left)
- Resolves an issue where `HTTPRoute` status conditions had a label of "Unknown" - added some parsing to check `status.parents`
> Some UI Fixes

- src/components/DropdownWithKebab.tsx
- src/components/KuadrantRateLimitPolicyCreatePage.tsx
> Remove form view from RLP until 1.x

- install.yaml
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/119
> consoleplugin v1

- src/components/ResourceList.tsx
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/127
> GW status: enforced if affected by any policies succesfully

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Dockerfile
- Dockerfile updates
- update Dockerfiles to update deps on build
- Use `:latest` base images
- CI: update builds to build multi-arch (`amd64` + `arm64`).
> dockerfile updates

- src/components/DropdownWithKebab.tsx
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/125
> Overview: edit Gateway/HTTPRoutes links broken

- src/components/KuadrantRateLimitPolicyCreatePage.tsx
Re: https://github.com/Kuadrant/kuadrant-console-plugin/issues/148
> Update RLP sample

- package.json
- src/components/KuadrantOverviewPage.tsx
- src/components/KuadrantPoliciesPage.tsx
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/152
> dev vs admin perspectives

- locales/en/plugin__kuadrant-console-plugin.json
- src/components/KuadrantOverviewPage.tsx
- src/constants/links.ts
Resolves: https://github.com/Kuadrant/kuadrant-console-plugin/issues/154
> add blank target, remove some broken links

- downstream.js
- package.json
> replacements update

- src/components/KuadrantPoliciesPage.tsx
Fixed the horizontal navigation automatically rendering the all policies tab when a … namespace is chosen rather then staying on the previous specified navigation tab
https://github.com/user-attachments/assets/0b42ea07-c742-4d62-be38-3c7ef04a03f9
> Fixed horizontal navigation

- docs/status-labels.md
Ref: https://github.com/Kuadrant/kuadrant-console-plugin/issues/187
> doc: status labels and conditions in the console plugin

- src/components/PolicyTopologyPage.tsx
Re: https://github.com/Kuadrant/kuadrant-console-plugin/issues/196
- Dynamically loads details about cluster resources via API discovery, so we can map Kinds to latest Groups and Versions
- Adds a new helper to warm a cache with this info on `<Topology/>` mount
- Some resources on cluster commonly shown by topology are ambiguous (e.g. ``dnsrecords.kuadrant.io` vs `dnsrecords.ingress.operator.openshift.io`)
Later on, this may morph into something more reusable as a general React hook for parts of the plugin
To verify:
- Click "Go to Resource" on any item in topology.
> 196 gvk discovery

- package.json
- yarn.lock
`"http-proxy-middleware": "2.0.7"`
> deps: bump http-proxy-middleware

- locales/en/plugin__kuadrant-console-plugin.json
- src/components/KuadrantOverviewPage.tsx
As discussed and agreed with ux and suggestion from @smccarthy-ie 
fyi @maleck13 Thanks for bringing this up.
> Change traffic text

- src/components/KuadrantOverviewPage.tsx
- src/components/kuadrant.css
4 commits addressing the bullet points listed in issue #227
> Small fixes to Gateway traffic error codes popover #227

- i18n-scripts/i18next-parser.config.js
Signed-off-by: Jason Madigan <jason@jasonmadigan.com>
> Fixing some i18n build issues

- downstream.js
Re: https://github.com/Kuadrant/kuadrant-console-plugin/issues/236
> link updates

- src/components/KuadrantOverviewPage.tsx
Updated `KuadrantOverviewPage.tsx` to refresh gateway counts every 5 seconds rather than needing a manual refresh for an update
> Gateway Bug #235

- src/components/PolicyTopologyPage.tsx
closes #106 
Verification
In one terminal window, run:
1. yarn install
2. yarn run start
In another terminal window, run:
1. oc login (requires [oc](https://console.redhat.com/openshift/downloads) and an [OpenShift cluster](https://console.redhat.com/openshift/create))
2. yarn run start-console
In browser:
1. open http://localhost:9000/
2. go to Kuadrant>Topology
3. Find the gateway or httpRoute and open the context menu for it (right-click on its icon):
4. Click on create policy and you will be redirected to the page for creating a policy from a default namespace:
>  Add an "Attach Policy" option to the actions list
