Kuadrant/kuadrant-console-plugin

- console-extensions.json
- package.json
- src/components/KuadrantPoliciesPage.tsx
- src/components/kuadrant.css
- tsconfig.json
> Add policies page

- src/components/namespace/NamespaceSelect.tsx
example usage:
```tsx
import NamespaceSelect from './namespace/NamespaceSelect';
// ...
const MyPage: React.FC = () => {
const [selectedNamespace, setSelectedNamespace] = React.useState('');
// ...
return (
<NamespaceSelect selectedNamespace={selectedNamespace} onChange={setSelectedNamespace} />
);
};
```
> Add NamespaceSelect component

- console-extensions.json
- locales/en/plugin__console-plugin-template.json
- package.json
- src/components/KuadrantRateLimitPolicyCreatePage.tsx
- src/components/httproute/HTTPRouteSelect.tsx
- src/components/httproute/types.ts
- src/components/kuadrant.css
- src/components/ratelimitpolicy/AddLimitModal.tsx
- src/components/ratelimitpolicy/types.ts
Closes #31 
Screenshots below.
A few fields have been purposefully left out of the form view as the API will be changing for kuadrant v1.
Future changes to the from are captured in https://github.com/Kuadrant/console-plugin/issues/68
In the interim, an info message is shown to direct the user to the yaml view for more complex limits configuration beyond simple limits.
### Limits in form
### Yaml editor
> Add RateLimitPolicy create page

- src/components/KuadrantRateLimitPolicyCreatePage.tsx
- src/components/kuadrant.css
- src/components/ratelimitpolicy/LimitSelect.tsx
Small refactor to move the limit selector pieces fully out to a separate component.
Also uses the [label pattern](https://www.patternfly.org/components/label) from patternfly now.
## Before
*no limits*
*limits added*
## After
*no limits*
*limits added*
> Move Limit selector out to separate component

- .github/workflows/build.yaml
- Dockerfile
- README.md
- package-lock.json
- package.json
- yarn.lock
- **Build + readme updates**
- **GH action for builds**
> console plugin install

- src/components/KuadrantOverviewPage.tsx
- src/components/ResourceList.tsx
Status / condition icons for policies: resolves https://github.com/Kuadrant/console-plugin/issues/72
TODO:
> Status condition labels

- src/components/KuadrantDNSPolicyCreatePage.tsx
- src/components/KuadrantPoliciesPage.tsx
- src/components/ResourceList.tsx
- src/components/kuadrant.css
- Set the background to white in light mode and regular gray in dark mode.
- **Previously:** The background was gray for light mode, which differed from other resource forms in console.
- **Old:**
- **New:**
---
- **Changes:**
- Removed extra padding around policy lists
- **Old:**
- **New:**
---
- **Changes:**
- Aligned the create buttons with the filter box.
- Removed odd padding beneath the create buttons
- **Old:**
- **New:**
---
> Some UI fixes

- src/components/KuadrantAuthPolicyCreatePage.tsx
- src/components/KuadrantPoliciesPage.tsx
- src/components/KuadrantRateLimitPolicyCreatePage.tsx
- src/components/KuadrantTLSCreatePage.tsx
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/92
> Add global picker for: AuthPolicy, TLSPolicy and RateLimitPolicy

- console-extensions.json
- install.yaml
- src/components/KuadrantAuthPolicyCreatePage.tsx
- src/components/KuadrantDNSPolicyCreatePage.tsx
- src/components/KuadrantOverviewPage.tsx
- src/components/KuadrantPoliciesPage.tsx
- src/components/KuadrantRateLimitPolicyCreatePage.tsx
- src/components/KuadrantTLSCreatePage.tsx
- src/components/PolicyTopologyPage.tsx
- src/utils/latest.tsx
- `ConsolePlugin` resource bump**
- `console-extensions.json` updates: reorder, and rev APIs for v1
- topology: ignore actions for meta-resources
- topology: nodesep change
- topology: Additional graph filtering for unaassociated policies, filter cert-manager resources
- centralise version refs
> Policy topology fixes, centralise CRD versioning refs

- .github/workflows/build.yaml
- .github/workflows/issues.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
> actions: fixup

- .github/workflows/i18n.yaml
- locales/en/plugin__kuadrant-console-plugin.json
- src/components/KuadrantOverviewPage.tsx
- src/components/kuadrant.css
> adding create resource button to overview page

- locales/en/plugin__kuadrant-console-plugin.json
- src/components/KuadrantPoliciesPage.tsx
Removing the info box as i don't think it's needed. When thinking of what to say felt like I was stating the obvious, no other resource in similar layouts has them either.
> removing info box

- src/components/PolicyTopologyPage.tsx
Two changes:
- Add a way to filter "connected" nodes from the graph (e.g. `GatewayClass`
- Nudge the `Kuadrant` resource into the `Kuadrant internals` node group
Before:
After:
> topology: add gatewayclass filtering

- src/components/ResourceList.tsx
Before:
After:
Gateway:
`[{"lastTransitionTime":"2024-11-07T13:00:17Z","message":"Object affected by TLSPolicy [gateway-system/tls]","observedGeneration":1,"reason":"Accepted","status":"True","type":"kuadrant.io/TLSPolicyAffected"},{"lastTransitionTime":"2024-11-07T13:00:17Z","message":"Object affected by DNSPolicy [gateway-system/dnspolicy gateway-system/dnspolicy-t1b gateway-system/dnspolicy-t1a]","observedGeneration":1,"reason":"Accepted","status":"True","type":"kuadrant.io/DNSPolicyAffected"},{"lastTransitionTime":"2024-11-07T13:00:13Z","message":"Route was valid, bound to 4 parents","observedGeneration":1,"reason":"Accepted","status":"True","type":"Accepted"},{"lastTransitionTime":"2024-11-07T13:00:14Z","message":"All references …
> Fix for Gateways/HTTPRoutes not marked as enforced

- install.yaml
- src/components/PolicyTopologyPage.tsx
- src/utils/latest.tsx
> Adding more Kinds for Authorinos, Limitadors and Kuadrants. Hide DNSRecords

- src/components/PolicyTopologyPage.tsx
- src/utils/latest.tsx
Hiding a couple more internals
> topology: more internals

- downstream.js
- locales/en/plugin__kuadrant-console-plugin.json
- src/components/KuadrantOverviewPage.tsx
- src/constants/links.ts
> add secure, protect connect guide link to learning resources

- RELEASE.md
- package.json
Added a `RELEASE.md` and bumped to dev version
> 0.15.0-dev and RELEASE notes

- Dockerfile
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/175 - see that issue for more details.
> Aligning docker builds

- src/components/PolicyTopologyPage.tsx
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/181
> topology lookup URI broken

- install.yaml
- package.json
Related issue: https://github.com/Kuadrant/kuadrant-console-plugin/issues/166
Adds a flag to get `console` to preload i18n resources before rendering the plugin
Related operator PR: https://github.com/Kuadrant/kuadrant-operator/pull/1139
> add i18n preload flag for ConsolePlugin

- locales/en/plugin__kuadrant-console-plugin.json
- src/components/DropdownWithKebab.tsx
- src/components/KuadrantOverviewPage.tsx
- src/components/KuadrantPoliciesPage.tsx
- src/components/NoPermissionsView.tsx
- src/components/PolicyTopologyPage.tsx
- src/components/ResourceList.tsx
- src/utils/getModelFromResource.ts
Resolves https://github.com/Kuadrant/kuadrant-console-plugin/issues/205
To verify, create users per: https://github.com/Kuadrant/kuadrant-console-plugin/pull/215
To test, I also create a rolebinding with perms for namespaces and authpolicies, for a user called `rbactest1`:
```bash
kubectl apply -f - <<'EOF'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: authpolicy-reader
rules:
- apiGroups: ["kuadrant.io"]
resources: ["authpolicies"]
verbs: ["list", "get", "watch"]
- apiGroups: [""]
resources: ["namespaces"]
verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: read-authpolicies-binding
subjects:
- kind: User
name: rbactest1
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: ClusterRole
name: …
```
> RBAC for Policy List pages

- src/components/KuadrantOverviewPage.tsx
- src/components/kuadrant.css
Ref: https://github.com/Kuadrant/kuadrant-console-plugin/issues/254
While testing on OCP 4.19, user reported some visual bugs in Overview page of the plugin.
- Coloring on texts in Getting started resources section seems to not apply
- Background coloring in lists of resources seem to not match the new OCP 4.19 background color
1. Visit Kuadrant Overview Page using side menu
2. Note the differences using OCP 4.17/4.18 overview pages as comparison
> DRAFT: Visual coloring glitches on Plugin Overview Page

- console-extensions.json
- package.json
- src/components/KuadrantTLSCreatePage.tsx
- src/components/dnspolicy/useDNSPolicyActions.tsx
- src/components/tlspolicy/useTLSPolicyActions.tsx
Searching for TLS/DNS policies and clicking on three dots should now bring you to the custom form page when editing.
> fix dns/tls policy edit to use forms
